### ISSUE TITLE
Stuck in _DoubleExceptionVector

### ISSUE THREAD

**Issue by maxgerhardt** [rsaxvc/sysprogs-esp8266-openocd#1]
I've read your blog post in https://rsaxvc.net/blog/2020/2/22/Setting_up_ESP8266_for_sample-based_profiling_and_debugging.html. I have the OpenOCD version compiled and, using a Adafruit FT232H breakout, connected to NodeMCUv2 dev borad.

My OpenOCD config file is
```ini
adapter driver ftdi
ftdi_vid_pid 0x0403 0x6014
ftdi_layout_init 0x4008 0x400b
ftdi_layout_signal nTRST -data 0x0020
ftdi_layout_signal nSRST -oe 0x0010
reset_config srst_pulls_trst
```
and ADBUS0-3 are TCK, TDI, TDO, TMS, with ADBUS4 connected to "RST" of the NodeMCU.

>/home/max/sysprogs-esp8266-openocd/release/usr/local/bin/openocd -s share/openocd/scripts/ -f interface/ftdi/adafruit.cfg -f target/esp8266.cfg -c set esp8266_autofeed_watchdog enable

I upload (via regular serial / esptool.py) a firmware exactly like in your blog post. For xtensa-lx106-gdb, I'm using the one in https://docs.espressif.com/projects/esp8266-rtos-sdk/en/latest/get-started/linux-setup.html.

My problem is that I cannot get the debugger to halt in Arduino firmware code. Instead, it always halts in the double exception vector.

```
Program
 received signal SIGTRAP, Trace/breakpoint trap.
0x40100070 in _DoubleExceptionVector ()
$ where
#0  0x40100070 in _DoubleExceptionVector ()
#1  0x40000f68 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
$ x/10i $pc
=> 0x40100070 <_DoubleExceptionVector>:	break	1, 4
   0x40100073 <_DoubleExceptionVector+3>:	j	0x40100070 <_DoubleExceptionVector>
```

Do you have instructions for setting it up with Arduino, specifically which GDB version is used, which GDB init commands are used and what OpenOCD commands are used?

**Comment by maxgerhardt** [comment]
Hm, the problem is with the reset command it seems. If I don't do `monitor reset halt` it seems to work.

**Comment by maxgerhardt** [comment]
Reset not working was through wrong ftdi_layout commands. This works fine and resets.

```
# ADBUS 0-3: TCKm TDI, TDO, TMS
ftdi_layout_init 0xfff8 0xfffb
# ACBUS0
ftdi_layout_signal nTRST -data 0x0100 -oe 0x0100
# ACBUS1
ftdi_layout_signal nSRST -data 0x0200 -oe 0x0200
reset_config trst_and_srst trst_push_pull srst_push_pull
adapter srst delay 200
jtag_ntrst_delay 200
adapter srst pulse_width 50
jtag_ntrst_assert_width 50
```

**Comment by rsaxvc** [comment]
Hi Max! I had forgotten about this entirely. I'm glad you figured it out and got it working.
